# Generated by Django 5.2.16 on 2026-07-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_usertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('state', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='editor.usertemplate')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('user_template', 'version')},
            },
        ),
    ]
