# Generated by Django 5.2.16 on 2026-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_uploadedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
