# Generated by Django 5.2.16 on 2026-07-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedasset',
            name='placeholder_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
