# Generated by Django 5.2.16 on 2026-08-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_sitebundle_bundleasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
