# Generated by Django 5.2.16 on 2026-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_clean_legacy_buy_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebundle',
            name='entrypoint_path',
            field=models.CharField(default='index.html', max_length=255),
        ),
        migrations.AddField(
            model_name='sitebundle',
            name='is_hosted_locally',
            field=models.BooleanField(default=False),
        ),
    ]
