# Generated by Django 5.2.16 on 2026-08-04 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0011_sitebundle_bundleasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='VercelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('deployment_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('state', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='editor.sitebundle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
