# Generated by Django 5.2.16 on 2026-07-24 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0007_usertemplate_is_published_usertemplate_public_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen'], name='analytics_a_last_se_b4c4c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('entry_path', models.CharField(default='/', max_length=200)),
                ('exit_target', models.CharField(blank=True, max_length=120)),
                ('viewport_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_sessions', to='editor.usertemplate')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.analyticsvisitor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pageview', 'Page view'), ('heartbeat', 'Heartbeat'), ('click', 'Click'), ('move', 'Pointer sample'), ('page_exit', 'Page exit')], max_length=16)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('x', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.analyticssession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'kind', 'occurred_at'], name='analytics_a_session_f9f23c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x__isnull', True), models.Q(('x__gte', 0), ('x__lte', 1)), _connector='OR'), name='analytics_event_x_between_zero_and_one'), models.CheckConstraint(condition=models.Q(('y__isnull', True), models.Q(('y__gte', 0), ('y__lte', 1)), _connector='OR'), name='analytics_event_y_between_zero_and_one')],
            },
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['template', 'started_at'], name='analytics_a_templat_f1a761_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['visitor', 'started_at'], name='analytics_a_visitor_b88640_idx'),
        ),
    ]
