# Generated by Django 5.2.16 on 2026-07-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_multi_gateway_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercadopago'), ('paypal', 'Paypal'), ('braintree', 'Braintree'), ('wompi', 'Wompi'), ('payu', 'Payu'), ('epayco', 'Epayco'), ('bold', 'Bold'), ('none', 'None')], default='stripe', max_length=16),
        ),
    ]
